# Generated by Django 3.2 on 2021-05-06 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usertimestamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimestamp',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_constrain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertimestamp',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_constrain', to=settings.AUTH_USER_MODEL),
        ),
    ]
