# Generated by Django 3.2.2 on 2021-05-11 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usertimestamp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('usertimestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usertimestamp.usertimestamp')),
                ('todo_title', models.CharField(max_length=255)),
                ('todo_status', models.CharField(choices=[('OP', 'Open'), ('IN', 'Inprogress'), ('BL', 'Block'), ('QA', 'QA'), ('RV', 'Review Code'), ('DN', 'Done')], default='OP', max_length=2)),
                ('todo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('usertimestamp.usertimestamp', models.Model),
        ),
    ]
